In [1]:
import ktrain
import numpy as np
import pandas as pd
from IPython.display import display, HTML
from ktrain import text

using Keras version: 2.2.4-tf


In [2]:
DATA_PATH = r'train.csv'
NUM_WORDS = 50000
MAXLEN = 264

In [3]:
(x_train, y_train), (x_test, y_test), preproc = text.texts_from_csv(DATA_PATH,
                      'Text',
                      label_columns = ['STRENGTHS','WEAKNESSES','OPPORTUNITIES','THREATS'],
                      preprocess_mode='bert',
                      val_filepath=None, 
                      max_features=NUM_WORDS,
                      maxlen=MAXLEN)

detected encoding: ISO-8859-3 (if wrong, set manually)
preprocessing train...
language: en


preprocessing test...
language: en


In [4]:
x_test[:5]

[array([[  101,  1996,  2194, ...,     0,     0,     0],
        [  101, 17473,  8089, ...,     0,     0,     0],
        [  101,  3811,  6975, ...,     0,     0,     0],
        ...,
        [  101,  2045,  2038, ...,     0,     0,     0],
        [  101,  5100,  1999, ...,     0,     0,     0],
        [  101,  2429,  2000, ...,     0,     0,     0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])]

In [5]:
y_test[:5]

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int64)

In [6]:
model = text.text_classifier('bert', train_data=(x_train, y_train), preproc=preproc)

Is Multi-Label? False
maxlen is 264
done.


In [7]:
learner = ktrain.get_learner(model, train_data=(x_train, y_train), batch_size=16)

In [8]:
learner.fit_onecycle(2e-5, 4)



begin training using onecycle policy with max lr of 2e-05...
Train on 2250 samples
Epoch 1/4
2250/2250 [==============================] - 1829s 813ms/sample - loss: 1.0817 - accuracy: 0.5413
Epoch 2/4
2250/2250 [==============================] - 1811s 805ms/sample - loss: 0.4932 - accuracy: 0.8231
Epoch 3/4
2250/2250 [==============================] - 1765s 785ms/sample - loss: 0.2972 - accuracy: 0.8911
Epoch 4/4
2250/2250 [==============================] - 1765s 785ms/sample - loss: 0.1565 - accuracy: 0.9502


In [9]:
learner.validate(val_data=(x_test, y_test), class_names=['S','W','O','T'])

              precision    recall  f1-score   support

           S       0.92      0.92      0.92        87
           W       0.83      0.82      0.83        55
           O       0.95      0.91      0.93        58
           T       0.89      0.94      0.91        50

    accuracy                           0.90       250
   macro avg       0.90      0.90      0.90       250
weighted avg       0.90      0.90      0.90       250



array([[80,  6,  1,  0],
       [ 4, 45,  1,  5],
       [ 3,  1, 53,  1],
       [ 0,  2,  1, 47]], dtype=int64)

In [10]:
predictor = ktrain.get_predictor(learner.model, preproc)

In [11]:
predictor.get_classes()

['STRENGTHS', 'WEAKNESSES', 'OPPORTUNITIES', 'THREATS']

In [12]:
df1 = pd.read_excel(r"test.xlsm",index=1)

In [13]:
df1.set_index("#id", inplace = True)

In [14]:
display(HTML(df1[15:16].to_html()))

In [15]:
predictor.predict(np.array(df1['Text'][15:16]))

['WEAKNESSES']

In [17]:
# let's save the predictor for later use
predictor.save(r'.\run264_16\saved_model_25k')

In [18]:
# reload the predictor
reloaded_predictor = ktrain.load_predictor(r'.\run264_16\saved_model_25k')

In [19]:
# make a prediction on the same document to verify it still works
results=reloaded_predictor.predict(np.array(df1['Text'][0:16]))

In [20]:
df1['Prediction']=results
display(HTML(df1.to_html()))